const app = document.querySelector('#app');
let cameraStream;
const lookupEndpoint = window.SCANLY_CONFIG?.lookupEndpoint?.trim();
const loadHistory = () => { try { return JSON.parse(localStorage.getItem('scanly-history') || '[]'); } catch { return []; } };
let scans = loadHistory();
const saveHistory = () => localStorage.setItem('scanly-history', JSON.stringify(scans));
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
const scanCard = item => `<a class="scan-card" href="#item/${encodeURIComponent(item.code)}"><div class="code">${item.image ? `<img src="${escapeHtml(item.image)}" alt="" />` : item.icon}</div><div><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.code)} · ${escapeHtml(item.time)}</small></div><span style="margin-left:auto;color:var(--muted)">›</span></a>`;
const scansThisWeek = () => { const weekAgo = Date.now() - 7 * 24 * 60 * 60 * 1000; return scans.filter(scan => new Date(scan.scannedAt || 0).getTime() >= weekAgo).length; };
const home = () => `<section class="hero"><div class="eyebrow" style="color:var(--lime)">Your everyday scanner</div><h1>Know what’s behind every barcode.</h1><p>Scan products, save what matters, and keep useful details close at hand.</p><a class="scan-action" href="#scan"><span>⌗</span>Scan a barcode</a></section><div class="section-head"><h2>Your activity</h2></div><div class="stats"><div class="stat"><strong>${scans.length}</strong><span>Total scans</span></div><div class="stat"><strong>${scansThisWeek()}</strong><span>This week</span></div><div class="stat"><strong>${scans.length}</strong><span>Products found</span></div></div><div class="section-head"><h2>Recent scans</h2><a class="link" href="#history">View all</a></div>${scans.length ? scans.slice(0, 2).map(scanCard).join('') : `<div class="empty compact"><div class="empty-icon">⌗</div><h2>No scans yet</h2><p>Scan a barcode to begin your history.</p></div>`}`;
const scan = () => `<section class="page-intro"><div class="eyebrow">Ready when you are</div><h1>Scan a barcode</h1><p>Position the barcode inside the frame. We’ll look up the product details.</p></section><section class="scanner" id="scanner"><div class="scanner-ui"></div><div class="scanner-label" id="scanner-status">Opening your camera…</div></section><div class="scan-options"><button class="option" id="manual"><span>⌨</span>Enter code manually</button><button class="option" id="image"><span>▧</span>Choose a photo</button></div>`;
const history = () => `<section class="page-intro"><div class="eyebrow">Your library</div><h1>Scan history</h1><p>Everything you’ve scanned, in one calm place.</p></section><div class="section-head"><h2>Recent scans</h2>${scans.length ? '<button class="link" id="clear-history">Clear history</button>' : ''}</div>${scans.length ? scans.map(scanCard).join('') : `<div class="empty"><div class="empty-icon">⌗</div><h2>Your history is clear</h2><p>Scan a barcode to add your first product.</p></div>`}`;
const settings = () => `<section class="page-intro"><div class="eyebrow">Make it yours</div><h1>Settings</h1><p>Control how Scanly works for you.</p></section><div style="margin-top:22px"><div class="setting"><div><b>Haptic feedback</b><small>Vibrate after a successful scan</small></div><button class="toggle on" aria-label="Toggle haptic feedback"><i></i></button></div><div class="setting"><div><b>Save scan history</b><small>Keep your recent scans on this device</small></div><button class="toggle on" aria-label="Toggle history saving"><i></i></button></div><div class="setting"><div><b>Dark appearance</b><small>Use the darker Scanly theme</small></div><button class="toggle" id="dark-toggle" aria-label="Toggle dark appearance"><i></i></button></div></div>`;
const loadingItem = code => `<a class="link" href="#history">← Back to history</a><div class="product-loading"><div class="loader"></div><h2>Looking up product</h2><p>Finding details for ${escapeHtml(code)}…</p></div>`;
const trafficLight = (name, value, low, medium) => { const amount = Number(value); const level = !Number.isFinite(amount) ? 'unknown' : amount <= low ? 'green' : amount <= medium ? 'amber' : 'red'; const display = Number.isFinite(amount) ? `${amount.toFixed(amount < 1 ? 2 : 1).replace(/\.0$/, '')}g` : '—'; return `<div class="traffic-light ${level}" aria-label="${name}: ${display} per 100 grams, ${level}"><span class="traffic-dot"></span><b>${name}</b><strong>${display}</strong><small>per 100g</small></div>`; };
const trafficLights = values => `<section class="traffic-section"><div class="section-head"><h2>Traffic lights</h2><span class="per-100">Per 100g</span></div><div class="traffic-lights">${trafficLight('Fat', values.fat, 3, 17.5)}${trafficLight('Saturates', values.saturates, 1.5, 5)}${trafficLight('Sugars', values.sugars, 5, 22.5)}${trafficLight('Salt', values.salt, 0.3, 1.5)}</div></section>`;
const productItem = product => `<a class="link" href="#history">← Back to history</a><div class="detail-hero">${product.image ? `<img src="${escapeHtml(product.image)}" alt="${escapeHtml(product.name)}" />` : '⌗'}</div><section class="page-intro"><div class="eyebrow">Product found</div><h1>${escapeHtml(product.name)}</h1><p>${escapeHtml(product.brand || 'Brand not listed')}</p></section><div class="detail-code">${escapeHtml(product.code)}</div><div class="product-grid"><div><span>Price</span><b>${escapeHtml(product.price || 'Not available')}</b></div><div><span>Nutri-Score</span><b class="grade">${escapeHtml(product.grade || '—')}</b></div></div>${trafficLights(product.traffic)}<div class="section-head"><h2>About this product</h2></div><p>${escapeHtml(product.description || 'No description is available for this product.')}</p><div class="info-list"><div><span>Product type</span><b>${escapeHtml(product.type || 'Product')}</b></div><div><span>Categories</span><b>${escapeHtml(product.categories || 'Not listed')}</b></div><div><span>Ingredients</span><b>${escapeHtml(product.ingredients || 'Not listed')}</b></div><div><span>Nutrition</span><b>${escapeHtml(product.nutrition || 'Not available')}</b></div></div><p class="data-note">The lookup searches Open Food Facts, Open Beauty Facts, Open Pet Food Facts, and Open Products Facts. Traffic-light colours use UK front-of-pack solid-food thresholds and are calculated from available per-100g data.</p>`;
const missingItem = code => `<a class="link" href="#history">← Back to history</a><div class="empty"><div class="empty-icon">⌗</div><h2>Product not found</h2><p>We couldn’t find details for barcode ${escapeHtml(code)} in the product catalogue.</p><button class="scan-action" id="try-another">Try another barcode</button></div>`;
const errorItem = () => `<a class="link" href="#history">← Back to history</a><div class="empty"><div class="empty-icon">!</div><h2>Couldn’t load product details</h2><p>Check your connection and try again.</p><button class="scan-action" id="retry-lookup">Try again</button></div>`;
function render() { cameraStream?.getTracks().forEach(track => track.stop()); cameraStream = undefined; const route = location.hash.slice(1) || 'home'; const [page, rawId] = route.split('/'); const id = decodeURIComponent(rawId || ''); app.innerHTML = page === 'scan' ? scan() : page === 'history' ? history() : page === 'settings' ? settings() : page === 'item' ? loadingItem(id) : home(); document.querySelectorAll('[data-nav]').forEach(link => link.classList.toggle('active', link.dataset.nav === page)); app.focus(); bindPage(page, id); }
function toast(message) { document.querySelector('.toast')?.remove(); const el = document.createElement('div'); el.className = 'toast'; el.textContent = message; document.body.append(el); setTimeout(() => el.remove(), 2800); }
function addToHistory(product) { const now = new Date(); const item = { name: product.name, code: product.code, time: `Today, ${now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`, scannedAt: now.toISOString(), image: product.image, icon: '⌗' }; scans = [item, ...scans.filter(scan => scan.code !== item.code)]; saveHistory(); }
async function lookupProduct(code) { if (!code) return; try { const fields = 'code,product_name,brands,image_front_url,generic_name,ingredients_text,categories,nutrition_grades,nutriments,product_type'; const source = lookupEndpoint || `https://world.openfoodfacts.org/api/v3.6/product/${encodeURIComponent(code)}.json?fields=${fields}&product_type=all`; const response = await fetch(lookupEndpoint ? `${lookupEndpoint}?barcode=${encodeURIComponent(code)}` : source); if (response.status === 404) { app.innerHTML = missingItem(code); document.querySelector('#try-another').onclick = () => location.hash = 'scan'; return; } if (!response.ok) throw new Error('Catalogue request failed'); const data = await response.json(); if (!(['success', 1].includes(data.status)) || !data.product) { app.innerHTML = missingItem(code); document.querySelector('#try-another').onclick = () => location.hash = 'scan'; return; } const p = data.product; const nutriments = p.nutriments || {}; const nutrition = nutriments['energy-kcal_100g'] ? `${nutriments['energy-kcal_100g']} kcal per 100g` : nutriments.energy ? `${nutriments.energy} kJ per 100g` : ''; const product = { code: p.code || code, name: p.product_name || p.generic_name || 'Unnamed product', brand: p.brands, image: p.image_front_url, description: p.generic_name, ingredients: p.ingredients_text, categories: p.categories, type: p.product_type?.replace(/^./, letter => letter.toUpperCase()), grade: p.nutrition_grades?.toUpperCase(), nutrition, traffic: { fat: nutriments.fat_100g, saturates: nutriments['saturated-fat_100g'], sugars: nutriments.sugars_100g, salt: nutriments.salt_100g ?? (nutriments.sodium_100g ? nutriments.sodium_100g * 2.5 : undefined) } }; addToHistory(product); app.innerHTML = productItem(product); } catch { app.innerHTML = errorItem(); document.querySelector('#retry-lookup').onclick = () => lookupProduct(code); } }
async function startCamera() { const status = document.querySelector('#scanner-status'); const video = document.createElement('video'); video.setAttribute('playsinline', ''); video.autoplay = true; try { if (!navigator.mediaDevices?.getUserMedia) throw new Error('Secure camera access unavailable'); cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } } }); video.srcObject = cameraStream; document.querySelector('#scanner').prepend(video); status.textContent = 'Align the barcode within the frame'; if ('BarcodeDetector' in window) { const detector = new BarcodeDetector({ formats: ['ean_13', 'ean_8', 'upc_a', 'upc_e', 'code_128', 'qr_code'] }); const detect = async () => { if (!cameraStream) return; const codes = await detector.detect(video); if (codes[0]) { location.hash = `item/${codes[0].rawValue}`; return; } requestAnimationFrame(detect); }; video.onloadeddata = detect; } else status.textContent = 'Camera ready — use manual entry if scanning is unavailable'; } catch { status.textContent = 'Camera needs HTTPS and permission — enter a code instead'; } }
function bindPage(page, id) { document.querySelectorAll('.toggle').forEach(button => button.onclick = () => button.classList.toggle('on')); if (page === 'item') lookupProduct(id); if (page === 'scan') { startCamera(); document.querySelector('#manual').onclick = () => { const code = prompt('Enter the barcode number'); if (code?.trim()) location.hash = `item/${encodeURIComponent(code.trim())}`; }; document.querySelector('#image').onclick = () => toast('Photo scanning can be connected here next.'); } document.querySelector('#clear-history')?.addEventListener('click', () => { scans = []; saveHistory(); render(); }); }
document.querySelector('#theme-toggle').onclick = () => document.body.classList.toggle('dark'); window.addEventListener('hashchange', render); render();
